# fly.toml file generated for seprem-back-end on 2023-04-12T10:28:42-03:00

app = "seprem-back-end"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports.http_options.response.headers]]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
